# NumPy

In [1]:
import numpy as np
import pandas as pd

## О массивах NumPy

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
arr = np.array([5,6,7,8], dtype = float)
arr.dtype

dtype('float64')

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.shape(arr)

(3, 3)

In [5]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована

array([6.95201586e-310, 6.95203209e-310, 0.00000000e+000, 0.00000000e+000,
       2.12199580e-314])

In [6]:
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [8]:
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

array([ 0,  7, 14])

In [11]:
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[3, 7, 0],
       [5, 8, 6],
       [3, 5, 0]])

In [13]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

### Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:

In [14]:
big_secret[:, -1].sum()

3154.332495807108

### Выделите из каждой строки массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после запятой:

In [15]:
big_secret[:, :5].diagonal().sum()

121.37188663699624

### Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [16]:
big_secret[:, -5:].diagonal().prod()

341505315559.2347

# Особенность индексирования

Важное отличие массивов NumPy от списков Python — при изменении среза или отдельных элементов все изменения касаются не только самого среза, но и падают в исходный массив, даже если перед внесением изменений срез был сохранён в виде отдельной переменной. Изначально NumPy проектировался для работы с большими массивами данных, поэтому при бесконтрольном копировании фрагментов массивов возникли бы проблемы с быстродействием и памятью.

In [17]:
my_array = np.random.randint(1, 100, (4, 6))
my_array

array([[90, 69, 15, 83, 24, 59],
       [10, 72, 66, 52,  6, 95],
       [22, 47,  9, 51,  1, 30],
       [87, 70, 33, 14, 53, 26]])

In [18]:
my_slice = my_array[1:3, 2:4]
my_slice[:] = 0

my_array

array([[90, 69, 15, 83, 24, 59],
       [10, 72,  0,  0,  6, 95],
       [22, 47,  0,  0,  1, 30],
       [87, 70, 33, 14, 53, 26]])

### Проверим знания! Продолжим работать с массивом big_secret. Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.

In [19]:
big_secret[1::2, 1::2] = 1
big_secret[::2, ::2] = -1

### Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.

In [20]:
big_secret[:, :5].diagonal().sum()

-1.0

### Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [21]:
big_secret[:, -5:].diagonal().prod()

-1.0

# Операции с массивами

Особенностью работы с массивами в NumPy является то, что возможности библиотеки позволяют выполнять любые математические действия с массивами без использования циклов for, благодаря чему вычисления производятся с большой скоростью. В NumPy над массивами можно производить все стандартные арифметические операции.

Операции выполняются поэлементно, поэтому для получения корректного результата размерность массивов должна быть одинаковой. Также можно производить математические операции между массивом и числом.

In [22]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2

print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


# Универсальные функции

Универсальными называют функции, которые выполняют поэлементные операции над данными, хранящимися в объектах ndarray.  Большинство универсальных функций относятся к унарным операциям и выполняются над каждым элементом массива по очереди. Унарные операции — это  и есть операции, которые выполняются над каждым элементом массива по очереди.

Рассмотрим список часто используемых универсальных функций NumPy. При вызове каждой из этих функций необходимо указывать название библиотеки NumPy: *np.isnan(имя_массива)*:

![NumPy Methods](./../../data/numpy_methods.png)

In [23]:
arr = np.array([-1.3,2,3,4,5,6,7,8,9])
np.exp(arr)

array([2.72531793e-01, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

![Exponent](./../../data/exponent.png)

[Экспонента](https://ru.wikipedia.org/wiki/%D0%AD%D0%BA%D1%81%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0)

# Изменение размерности массива

В некоторых задачах машинного обучения для подготовки данных к обработке нужно **изменить** исходную **форму** массива, например, преобразовать многомерный массив в одномерный, поменять местами строки и столбцы.

Замена местами строк и столбцов двумерного массива называется **транспонированием**. Для выполнения этой операции в NumPy используется метод T:

In [24]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Для **превращения** массива одной **размерности** в массив другой — обычно для преобразования одномерного массива в многомерный — используется метод **reshape**. Изменить размерность массива можно только в том случае, если число элементов в исходном и в целевом массиве совпадает:

In [25]:
my_array = np.random.randint(0, 10, 20)
my_array

array([6, 8, 3, 5, 2, 6, 8, 2, 4, 4, 9, 8, 6, 3, 6, 9, 8, 0, 8, 9])

In [26]:
my_array.reshape((4,5))

array([[6, 8, 3, 5, 2],
       [6, 8, 2, 4, 4],
       [9, 8, 6, 3, 6],
       [9, 8, 0, 8, 9]])

Для преобразования многомерного массива в одномерный используется метод **flatten**:

In [27]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [28]:
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

# Сравнения и маски

Научимся сравнивать элементы массива с числом и извлекать из него только те элементы, которые больше или меньше заданного числа. Для этого создадим массив размера 3х4, произвольно заполненный числами от 0 до 10. При создании массива используется генератор случайных чисел, так что у вас могут получиться другие значения:

In [29]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[9, 4, 8, 2],
       [3, 4, 1, 1],
       [8, 5, 4, 5]])

In [30]:
my_array<5

array([[False,  True, False,  True],
       [ True,  True,  True,  True],
       [False, False,  True, False]])

In [31]:
my_array[my_array<5]

array([4, 2, 3, 4, 1, 1, 4])

Мы получили новый массив, заполненный значениями True/False в зависимости от того, меньше или больше пяти элемент, находящийся на соответствующей позиции в исходном массиве. Для того, чтобы получить элементы массива my_array, которые меньше пяти, воспользуемся кодом ниже. Отобранные элементы представляют собой одномерный массив.

**Маска** нужна для выбора только определенных **строк** или **столбцов** из всего массива и скрытия остальных. Маска в Python задаётся при помощи булевых 0 и 1, где 0 скрывает столбец или строку, а 1 оставляет ее на виду. Выведем первый и третрий столбец массива:

In [32]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[9, 8],
       [3, 1],
       [8, 4]])

# Сортировка двумерных массивов

В двумерных массивах можно выполнять сортировку элементов строк и столбцов:

Сортировка выполняется с помощью функции **sort**, в качестве параметров функция получает сам массив, а также номер оси (0 (для столбцов) или 1 (для строк)) , элементы которой необходимо отсортировать. 

Как можно отсортировать элементы строк и столбцов?

Отсортируем элементы строк:

In [33]:
my_array = np.random.randint(0, 10, (4, 6))
my_array

array([[1, 9, 5, 0, 6, 1],
       [4, 2, 5, 6, 7, 7],
       [9, 1, 7, 6, 7, 9],
       [6, 2, 5, 1, 0, 1]])

In [34]:
np.sort(my_array, axis=1)

array([[0, 1, 1, 5, 6, 9],
       [2, 4, 5, 6, 7, 7],
       [1, 6, 7, 7, 9, 9],
       [0, 1, 1, 2, 5, 6]])

In [35]:
np.sort(my_array, axis=0)

array([[1, 1, 5, 0, 0, 1],
       [4, 2, 5, 1, 6, 1],
       [6, 2, 5, 6, 7, 7],
       [9, 9, 7, 6, 7, 9]])

## Упражнения
Для выполнения упражнений из следующего блока мы будем использовать массив, созданный с помощью кода:

In [36]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T
great_secret

array([[ 0.        ,  4.64158883, 66.66666667],
       [ 1.        ,  4.65700951, 40.        ],
       [ 1.41421356,  4.67232873, 67.33333333],
       [ 1.73205081,  4.68754815, 40.4       ],
       [ 2.        ,  4.70266938, 68.        ],
       [ 2.23606798,  4.71769398, 40.8       ],
       [ 2.44948974,  4.73262349, 68.66666667],
       [ 2.64575131,  4.7474594 , 41.2       ],
       [ 2.82842712,  4.76220316, 69.33333333],
       [ 3.        ,  4.77685618, 41.6       ],
       [ 3.16227766,  4.79141986, 70.        ],
       [ 3.31662479,  4.80589553, 42.        ],
       [ 3.46410162,  4.82028453, 70.66666667],
       [ 3.60555128,  4.83458813, 42.4       ],
       [ 3.74165739,  4.84880759, 71.33333333],
       [ 3.87298335,  4.86294413, 42.8       ],
       [ 4.        ,  4.87699896, 72.        ],
       [ 4.12310563,  4.89097325, 43.2       ],
       [ 4.24264069,  4.90486813, 72.66666667],
       [ 4.35889894,  4.91868473, 43.6       ],
       [ 4.47213595,  4.93242415, 73.333

#### Сколько столбцов содержит массив great_secret?

In [37]:
great_secret.shape[1]

3

#### Чему равна сумма косинусов элементов первой строки массива great_secret? Ответ округлите до двух знаков после запятой.

In [38]:
np.sum(np.cos(great_secret[0]))

0.16006721889793019

#### Чему равна сумма элементов массива great_secret, значение которых больше 50?

In [39]:
np.sum(great_secret[great_secret>50])

5470.0

#### Переведите массив great_secret в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150? Скопируйте ответ из Jupyter Notebook без изменений.

In [40]:
great_secret.flatten()[150]

7.0710678118654755

#### Отсортируйте значения столбцов массива great_secret по возрастанию. Чему равна сумма элементов последней строки отсортированного массива? Ответ округлите до двух цифр после запятой.

In [41]:
np.sum(np.sort(great_secret, axis=0)[great_secret.shape[0]-1])

115.12148016521353

## Математические и статистические операции

Модуль NumPy содержит множество базовых статистических функций, которые помогают описать имеющиеся данные: среднее арифметическое (mean), медиана (median), стандартное отклонение (std), корреляция (corrcoef) и прочие. Давайте посмотрим, как они работают. 

Для изучения функций будем использовать набор данных, содержащих информацию об учениках шестого класса. Данные об учениках представлены в таблице:

![Students](./../../data/students.png)

In [42]:
stud = np.array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

stud

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

# Средние величины

#### Чему равно медианное значение массы тела школьников?

In [43]:
np.median(stud[:, 2])

42.0

#### На сколько среднее арифметическое массы тела школьников больше медианного значения для этого же показателя? Дайте ответ в килограммах с точностью до одной десятой кг.

In [44]:
np.round(np.mean(stud[:, 2]) - np.median(stud[:, 2]), 1)

1.8

# Коэффициент корреляции

Корреляция — статистическая взаимосвязь случайных величин. Мерой корреляции служит одноименный коэффициент, который показывает, насколько сильно связаны величины, он может быть положительным или отрицательным, а по модулю принимает значение от 0 до 1. Отрицательный коэффициент говорит о том, что случайные величины связаны, но при увеличении одной из них вторая уменьшается. Если коэффициент положительный, то величины изменяются в одном направлении.

Аналитики часто оперируют в своей работе данной величиной и ошибаются, делая ложные выводы о данных. Связано это с тем, что не всегда наличие корреляции между двумя показателями говорит о том, что между ними есть причинно-следственная связь.

Давайте узнаем, как связан рост и вес наших школьников, посчитав коэффициент корреляции столбцов матрицы:

In [45]:
corr = np.corrcoef(stud[:,1], stud[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

Полученный нами коэффициент корреляции составляет чуть больше 0.64. Это говорит о том, что между ростом и весом школьников существует положительная связь: более рослые ученики обычно имеют более высокую массу тела.

#### Между какой парой признаков в массиве students наблюдается минимальная корреляция?

In [46]:
# между ростом и массой тела
corr_h_w = np.corrcoef(stud[:,1], stud[:,2])

# между ростом и успеваемостью
corr_h_perf = np.corrcoef(stud[:, 1], stud[:, 3])

# между массой тела и успеваемостью
corr_w_perf = np.corrcoef(stud[:, 2], stud[:, 3])

print(corr_h_w)
print(corr_h_perf)
print(corr_w_perf)

[[1.         0.64314431]
 [0.64314431 1.        ]]
[[1.         0.46293714]
 [0.46293714 1.        ]]
[[1.         0.29801325]
 [0.29801325 1.        ]]


Ответ: между массой тела и успеваемостью = 0.29

# Показатели вариации

## Математическое ожидание
Среднее значение случайной величины при стремлении числа её измерений к бесконечности. Если число измерений конечно, то для оценки среднего значения величины используется среднее арифметическое.

## Дисперсия
мера разброса случайной величины относительно её математического ожидания. 

![Дисперсия](./../../data/disper.png)

Как следует из формулы, дисперсия случайной величины X равна математическому ожиданию квадрата отклонения случайной величины от ее математического ожидания. То есть, если величина дисперсии небольшая, значит, все числа в выборке имеют близкие друг к другу значения, а чем она больше — тем значительнее разброс показателей.

На практике при анализе выборок математическое ожидание, как правило, не известно. Поэтому вместо него используют оценку – среднее арифметическое. Расчет дисперсии производят по формуле:

![Дисперсия](./../../data/disper2.png)

где

s^2 – выборочная дисперсия, рассчитанная по данным наблюдений,

X – отдельные значения,

X̅– среднее арифметическое по выборке.

Стоит отметить, что у такого расчета дисперсии есть недостаток – она получается смещенной, т.е. ее математическое ожидание не равно истинному значению дисперсии. Подробней об этом здесь. Однако при увеличении объема выборки она все-таки приближается к своему теоретическому аналогу, т.е. является асимптотически не смещенной.

Простыми словами дисперсия – это средний квадрат отклонений. То есть вначале рассчитывается среднее значение, затем берется разница между каждым исходным и средним значением, возводится в квадрат, складывается и затем делится на количество значений в данной совокупности. Разница между отдельным значением и средней отражает меру отклонения. В квадрат возводится для того, чтобы все отклонения стали исключительно положительными числами и чтобы избежать взаимоуничтожения положительных и отрицательных отклонений при их суммировании. Затем, имея квадраты отклонений, просто рассчитываем среднюю арифметическую. Средний – квадрат – отклонений. Отклонения возводятся в квадрат, и считается средняя.

arr = [10, 20, 30, 40, 50, 60, 70]
mean = 40
s^2 = ((10-40) + (20-40) + (30-40) + (40-40) + (50-40) + (60-40) + (70-40))/7 = ((-30) + (-20) + (-10) + (0) + (10) + (20) + (30))/7


## Стандартное отклонение
Самый распространенный показатель рассеивания случайной величины относительно её математического ожидания.

![STD](./../../data/std.png)

Стандартное отклонение равно квадратному корню из дисперсии. Низкое стандартное отклонение показывает, что все значения в выборке сгруппированы около среднего значения.  Большой показатель этой величины говорит о том, что разброс значений большой. 

Узнаем, насколько разный у школьников рост, посчитав стандартное отклонение std:

In [47]:
std = np.std(stud[:,1])
std

11.083320801997928

Полученный результат показывает, что в этом классе одни дети уже начали активно расти, а другие ещё не вступили в период полового созревания. В результате разброс в росте большинства учеников составляет более 11 см от среднего арифметического.

![STD and Dispersion](./../../data/std_disper.png)

#### Используя имеющийся набор данных о школьниках, найдите, чему равно стандартное отклонение их средних баллов.

In [48]:
np.std(stud[:, 3])

0.4517742799230607

#### Посчитайте, чему равна дисперсия значений веса школьников.

Эту величину можно получить двумя способами: математически - используя определение дисперсии и известную функцию в блоке, или самостоятельно - используя подходящую функцию модуля NumPy.

In [49]:
step1 = np.mean(stud[:, 2])
step2 = stud[:, 2] - step1
step3 = step2**2
step4 = np.sum(step3)
step5 = step4/len(stud[:, 2])

print('Средне арифметическая:', step1)
print('Дисперсия равна:', step5)

Средне арифметическая: 43.8
Дисперсия равна: 60.36
