In [102]:
import numpy as np
import pandas as pd

# Линейная комбинация векторов

![linear_comb.png](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/linear_comb.png?raw=1)

In [103]:
# решение задачи в коде
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])

p*500 + v*100 + s*0

array([1800, 3000, 2700])

![null_linear_comb](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/null_linear_comb.png?raw=1)

![nv](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/nv.png?raw=1)

![nv2](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/nv2.png?raw=1)

### Задачи:

#### Юный предприниматель Вовочка мастерит ракеты на водном топливе и продает их. За 4 недели он смастерил 3, 4, 5 и 9 ракет, а продал 1, 5, 3 и 6 ракет соответственно.

На изготовление одной ракеты он тратит  рублей, а продаёт их по  рублей за штуку.

Найдите вектор прибыли Вовочки за эти 4 недели:

In [104]:
made = np.array([3, 4, 5, 9])
sold = np.array([1, 5, 3, 6])

revenue = sold*400 - made*200

print('Ответ:', ', '.join([str(r) for r in revenue]))

Ответ: -200, 1200, 200, 600


#### Какие системы векторов являются линейно зависимыми?

![lz](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/lz.png?raw=1)

# Скалярное произведение векторов

Всего есть четыре основных способа умножить векторы:

- Скалярное произведение. Результат — число. 
- Векторное произведение. Результат — вектор.
- Смешанное произведение. Результат — число. 
- Тензорное произведение. Результат — матрица.

![sp](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/sp.png?raw=1)

![sp2](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/sp2.png?raw=1)

In [105]:
# решение задачи выше в коде
a = np.array([65, 70, 120, 30])
b = np.array([0.4, 0.4, 0.2, 0.8])

np.dot(a, b)

102.0

## Длина вектора

![pv](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/pv.png?raw=1)

## Свойство скалярного произведения векторов (линейность)

![pvl](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/pvl.png?raw=1)

In [106]:
np.dot(np.array([4,5,-1]), np.array([2,0,1]))

7

# Матрицы

![matrix1](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix1.png?raw=1)
![matrix2](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix2.png?raw=1)
![matrix3](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix3.png?raw=1)
![matrix4](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix4.png?raw=1)
![matrix5](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix5.png?raw=1)
![matrix6](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix6.png?raw=1)
![matrix7](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix7.png?raw=1)
![matrix8](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix8.png?raw=1)
![matrix9](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix9.png?raw=1)
![matrix10](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix10.png?raw=1)

In [107]:
A = np.array([[1, -5, 3], [2, 2, 1], [0, 3, 1], [2, 4, 12]])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [108]:
A2 = np.matrix("1,-5;2,2;0,3")
A2

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

## Транспонирование матрицы
При транспонировании строки матрицы записываются в столбцы и матрица переворачивается.

In [109]:
A2

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [110]:
A2.T

matrix([[ 1,  2,  0],
        [-5,  2,  3]])

## Ранг матрицы

![matrix10](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix_rang.png?raw=1)

In [111]:
A = np.matrix("1,2,3; 4,5,6; 7,8,10")

In [112]:
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])

In [113]:
np.linalg.det(A)

-2.9999999999999996

In [114]:
np.linalg.det(A) == np.linalg.det(A.T)

True

**Задача**

![task1](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/task1.png?raw=1)

In [115]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1,v2,v3]).T

In [116]:
A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9],
       [1, 1, 1]])

In [117]:
np.linalg.matrix_rank(A)

2

Мы видим, что ранг системы равен 2, а векторов в ней 3, значит, система линейно зависима. В качестве базиса можем взять любые два вектора.

Свойства ранга
1. Если  А — прямоугольная матрица размера m × k, то rk(A) ≤ min(m, k).
2. Если rk(A) = min(m, k), то А —матрица максимального ранга.
3. Квадратная матрица А размера n × n обратима, если:
  - det(A) ≠ 0
  - столбцы (или строки) матрицы А линейно независимы 
  - rk(A) = n
4. Квадратная матрица А размера n × n вырождена, если:
  - rk(A) < n
  - Чем меньше rk(A), тем более вырождена A

**Для успешного построения регрессий необходимо научиться избавляться от линейной зависимости**

### Задача

![task2](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/task2.png?raw=1)

In [118]:
v1 = np.array([4,0])
v2 = np.array([1,1])
v3 = np.array([6,4])
A = np.array([v1,v2,v3]).T

In [119]:
A

array([[4, 1, 6],
       [0, 1, 4]])

In [120]:
np.linalg.matrix_rank(A)

2

Мы видим, что ранг системы равен 2, а векторов в ней 3, значит, система линейно зависима.

In [121]:
print(np.linalg.matrix_rank(np.array([v1,v2]).T))
print(np.linalg.matrix_rank(np.array([v1,v3]).T))
print(np.linalg.matrix_rank(np.array([v2,v3]).T))

2
2
2


Ответ: Попарно линейно независимы (то есть каждая пара линейно независима)

### Задача

![task3](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/task3.png?raw=1)

In [122]:
v1 = np.array([4,1])
v2 = np.array([0,0])
A = np.array([v1,v2]).T

In [123]:
A

array([[4, 0],
       [1, 0]])

In [124]:
np.linalg.matrix_rank(A)

1

Мы видим, что ранг системы равен 1, а векторов в ней 2, значит, система линейно зависима.

In [125]:
np.linalg.det(A)

0.0

Квадратная матрица обратима тогда и только тогда, когда она невырождена, то есть её определитель не равен нулю.

### Задача



In [126]:
a = np.array([4,1,0])
b = np.array([-1,4,0])
c = np.array([0,0,1])

#### Попарно линейно независимы (то есть каждая пара неколлинеарна) (Да)

In [127]:
np.linalg.matrix_rank(np.array([a,b]).T)

2

In [128]:
np.linalg.matrix_rank(np.array([a,c]).T)

2

In [129]:
np.linalg.matrix_rank(np.array([b,c]).T)

2

#### Линейно независимы в целом (Да)

In [130]:
np.linalg.matrix_rank(np.array([a,b,c]).T)

3

#### Попарно ортогональны (то есть каждая пара ортогональна) (Да)

Вектора ортогональны если:
**a · b = ax · bx + ay · by + az · bz = 0**

В Python: **a.dot(b)**

In [134]:
a.dot(b)

0

In [135]:
a.dot(c)

0

In [136]:
b.dot(c)

0

### Задача

![task4](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/task4.png?raw=1)

In [137]:
A = np.matrix("1,0,3,5; 0,4,5,5; 0,0,0,0; 0,0,0,0")
B = np.matrix("1,0,3,5; 0,4,5,5; 0,0,0,4; 0,0,0,0")

In [138]:
np.linalg.matrix_rank(A)

2

In [139]:
np.linalg.matrix_rank(B)

3