In [21]:
import numpy as np
import pandas as pd

# Линейная комбинация векторов

![linear_comb.png](./img/linear_comb.png)

In [3]:
# решение задачи в коде
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])

p*500 + v*100 + s*0

array([1800, 3000, 2700])

![null_linear_comb](./img/null_linear_comb.png)

![nv](./img/nv.png)

![nv2](./img/nv2.png)

### Задачи:

#### Юный предприниматель Вовочка мастерит ракеты на водном топливе и продает их. За 4 недели он смастерил 3, 4, 5 и 9 ракет, а продал 1, 5, 3 и 6 ракет соответственно.

На изготовление одной ракеты он тратит  рублей, а продаёт их по  рублей за штуку.

Найдите вектор прибыли Вовочки за эти 4 недели:

In [4]:
made = np.array([3, 4, 5, 9])
sold = np.array([1, 5, 3, 6])

revenue = sold*400 - made*200

print('Ответ:', ', '.join([str(r) for r in revenue]))

Ответ: -200, 1200, 200, 600


#### Какие системы векторов являются линейно зависимыми?

![lz](./img/lz.png)

# Скалярное произведение векторов

Всего есть четыре основных способа умножить векторы:

- Скалярное произведение. Результат — число. 
- Векторное произведение. Результат — вектор.
- Смешанное произведение. Результат — число. 
- Тензорное произведение. Результат — матрица.

![sp](./img/sp.png)

![sp2](./img/sp2.png)

In [5]:
# решение задачи выше в коде
a = np.array([65, 70, 120, 30])
b = np.array([0.4, 0.4, 0.2, 0.8])

np.dot(a, b)

102.0

## Длина вектора

![pv](./img/pv.png)

## Свойство скалярного произведения векторов (линейность)

![pvl](./img/pvl.png)

In [6]:
np.dot(np.array([4,5,-1]), np.array([2,0,1]))

7

# Матрицы

![matrix1](./img/matrix1.png)
![matrix2](./img/matrix2.png)
![matrix3](./img/matrix3.png)
![matrix4](./img/matrix4.png)
![matrix5](./img/matrix5.png)
![matrix6](./img/matrix6.png)
![matrix7](./img/matrix7.png)
![matrix8](./img/matrix8.png)
![matrix9](./img/matrix9.png)
![matrix10](./img/matrix10.png)

In [7]:
A = np.array([[1, -5, 3], [2, 2, 1], [0, 3, 1], [2, 4, 12]])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [8]:
A2 = np.matrix("1,-5;2,2;0,3")
A2

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

## Транспонирование матрицы
При транспонировании строки матрицы записываются в столбцы и матрица переворачивается.

In [9]:
A2

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [153]:
A2.T

matrix([[ 1,  2,  0],
        [-5,  2,  3]])