In [1]:
import numpy as np
import pandas as pd

# Линейная комбинация векторов

![linear_comb.png](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/linear_comb.png?raw=1)

In [2]:
# решение задачи в коде
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])

p*500 + v*100 + s*0

array([1800, 3000, 2700])

![null_linear_comb](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/null_linear_comb.png?raw=1)

![nv](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/nv.png?raw=1)

![nv2](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/nv2.png?raw=1)

### Задачи:

#### Юный предприниматель Вовочка мастерит ракеты на водном топливе и продает их. За 4 недели он смастерил 3, 4, 5 и 9 ракет, а продал 1, 5, 3 и 6 ракет соответственно.

На изготовление одной ракеты он тратит  рублей, а продаёт их по  рублей за штуку.

Найдите вектор прибыли Вовочки за эти 4 недели:

In [3]:
made = np.array([3, 4, 5, 9])
sold = np.array([1, 5, 3, 6])

revenue = sold*400 - made*200

print('Ответ:', ', '.join([str(r) for r in revenue]))

Ответ: -200, 1200, 200, 600


#### Какие системы векторов являются линейно зависимыми?

![lz](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/lz.png?raw=1)

# Скалярное произведение векторов

Всего есть четыре основных способа умножить векторы:

- Скалярное произведение. Результат — число. 
- Векторное произведение. Результат — вектор.
- Смешанное произведение. Результат — число. 
- Тензорное произведение. Результат — матрица.

![sp](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/sp.png?raw=1)

![sp2](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/sp2.png?raw=1)

In [4]:
# решение задачи выше в коде
a = np.array([65, 70, 120, 30])
b = np.array([0.4, 0.4, 0.2, 0.8])

np.dot(a, b)

102.0

## Длина вектора

![pv](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/pv.png?raw=1)

## Свойство скалярного произведения векторов (линейность)

![pvl](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/pvl.png?raw=1)

In [5]:
np.dot(np.array([4,5,-1]), np.array([2,0,1]))

7

# Матрицы

![matrix1](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix1.png?raw=1)
![matrix2](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix2.png?raw=1)
![matrix3](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix3.png?raw=1)
![matrix4](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix4.png?raw=1)
![matrix5](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix5.png?raw=1)
![matrix6](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix6.png?raw=1)
![matrix7](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix7.png?raw=1)
![matrix8](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix8.png?raw=1)
![matrix9](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix9.png?raw=1)
![matrix10](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix10.png?raw=1)

In [6]:
A = np.array([[1, -5, 3], [2, 2, 1], [0, 3, 1], [2, 4, 12]])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [7]:
A2 = np.matrix("1,-5;2,2;0,3")
A2

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

## Транспонирование матрицы
При транспонировании строки матрицы записываются в столбцы и матрица переворачивается.

In [8]:
A2

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [9]:
A2.T

matrix([[ 1,  2,  0],
        [-5,  2,  3]])

## Ранг матрицы

![matrix10](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/matrix_rang.png?raw=1)

In [10]:
A = np.matrix("1,2,3; 4,5,6; 7,8,10")

In [11]:
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])

In [20]:
np.linalg.det(A)

-2.9999999999999996

In [12]:
np.linalg.det(A) == np.linalg.det(A.T)

True

**Задача**

![task1](https://github.com/ekalachev/skill_factory/blob/master/lessons/module_3/math/img/task1.png?raw=1)

In [ ]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1,v2,v3])