# Скалярное произведение векторов

In [1]:
import numpy as np

In [2]:
a = np.array([65, 70, 120, 30])
b = np.array([0.4, 0.4, 0.2, 0.8])

In [3]:
np.dot(a, b)

102.0

# Матрицы

In [6]:
A = np.array([[1, -5, 3], [2, 2, 1], [0, 3, 1], [2, 4, 12]])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [7]:
A2 = np.matrix("1,-5;2,2;0,3")
A2

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

## Транспонирование матрицы
При транспонировании строки матрицы записываются в столбцы и матрица переворачивается.

In [9]:
A2

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [10]:
A2.T

matrix([[ 1,  2,  0],
        [-5,  2,  3]])

## Умножение матриц

Операция умножения двух матриц возможна только в том случае, если число столбцов в первой матрице равно числу строк второй матрицы.

Если матрица А содержит *n* строк, а матрица В содержит  *l* столбцов, то результатом их умножения будет матрица С размером `n * l`

Умножение матриц *некоммутативно*, от есть АВ != ВА.

In [15]:
A = np.matrix('1,-5;2,2;0,3')
B = np.matrix('3,1,0;-1,0,2')

display(A)
display(B)

np.dot(A, B)

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])