In [21]:
import numpy as np
import pandas as pd

# Линейная комбинация векторов

![linear_comb.png](./img/linear_comb.png)

In [3]:
# решение задачи в коде
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])

p*500 + v*100 + s*0

array([1800, 3000, 2700])

![null_linear_comb](./img/null_linear_comb.png)

![nv](./img/nv.png)

![nv2](./img/nv2.png)

### Задачи:

#### Юный предприниматель Вовочка мастерит ракеты на водном топливе и продает их. За 4 недели он смастерил 3, 4, 5 и 9 ракет, а продал 1, 5, 3 и 6 ракет соответственно.

На изготовление одной ракеты он тратит  рублей, а продаёт их по  рублей за штуку.

Найдите вектор прибыли Вовочки за эти 4 недели:

In [4]:
made = np.array([3, 4, 5, 9])
sold = np.array([1, 5, 3, 6])

revenue = sold*400 - made*200

print('Ответ:', ', '.join([str(r) for r in revenue]))

Ответ: -200, 1200, 200, 600


#### Какие системы векторов являются линейно зависимыми?

![lz](./img/lz.png)

# Скалярное произведение векторов

Всего есть четыре основных способа умножить векторы:

- Скалярное произведение. Результат — число. 
- Векторное произведение. Результат — вектор.
- Смешанное произведение. Результат — число. 
- Тензорное произведение. Результат — матрица.

![sp](./img/sp.png)

![sp2](./img/sp2.png)

In [5]:
# решение задачи выше в коде
a = np.array([65, 70, 120, 30])
b = np.array([0.4, 0.4, 0.2, 0.8])

np.dot(a, b)

102.0

## Длина вектора

![pv](./img/pv.png)

## Свойство скалярного произведения векторов (линейность)

![pvl](./img/pvl.png)

In [6]:
np.dot(np.array([4,5,-1]), np.array([2,0,1]))

7

# Матрицы

In [7]:
A = np.array([[1, -5, 3], [2, 2, 1], [0, 3, 1], [2, 4, 12]])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [8]:
A2 = np.matrix("1,-5;2,2;0,3")
A2

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

## Транспонирование матрицы
При транспонировании строки матрицы записываются в столбцы и матрица переворачивается.

In [9]:
A2

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [10]:
A2.T

matrix([[ 1,  2,  0],
        [-5,  2,  3]])

## Умножение матриц

Операция умножения двух матриц возможна только в том случае, если число столбцов в первой матрице равно числу строк второй матрицы.

Если матрица А содержит *n* строк, а матрица В содержит  *l* столбцов, то результатом их умножения будет матрица С размером `n * l`

Умножение матриц *некоммутативно*, от есть АВ != ВА.

In [11]:
A = np.matrix('1,-5;2,2;0,3')
B = np.matrix('3,1,0;-1,0,2')

display(A)
display(B)

np.dot(A, B)

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [12]:
p = np.array([4,5])
v = np.array([2,1])
s = np.array([1,0])

p*2 + v*-3 + s*5

array([7, 7])

In [22]:
df = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [29]:
df.iloc[4]

1.Rent              40
2.Area              33
3.Rooms              1
4.Floor              6
5.Demo two weeks    20
6.Liv.Area          16
Name: 4, dtype: int64

In [32]:
df.iloc[:, 3].values

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [34]:
df.iloc[2, 3]

10

In [35]:
len(df)

9

In [42]:
','.join((df['2.Area'] - df['6.Liv.Area']).apply(lambda x: str(x)))

'13,12,15,13,17,9,20,15,25'

In [48]:
','.join((df['1.Rent'] / 10 * 4).apply(lambda x: str(int(x))))

'26,28,48,14,16,20,40,36,34'

In [54]:
np.dot(df['5.Demo two weeks'], np.array([10, 20, 30, 15, 5, 40, 20, 8, 20]))

1348

In [55]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [58]:
print(np.dot(u, v))
print(np.dot(v, w))
print(np.dot(u, w))

0
0
0


In [59]:
print(u@v)
print(v@w)
print(u@w)

0
0
0


In [68]:
(v*2 + w*-3)@u

0

In [84]:
[str(round(x, 3)) for x in u / np.linalg.norm(u)][2]

'0.289'

In [85]:
[str(round(x, 3)) for x in v / np.linalg.norm(v)][3]

'0.667'

In [86]:
[str(round(x, 3)) for x in w / np.linalg.norm(w)][0]

'0.213'